version: '3.3'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - frontend
