# Generated by Django 3.2.8 on 2021-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20211022_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('russian',)},
        ),
        migrations.AddField(
            model_name='user',
            name='known_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='known_list',
            field=models.CharField(default='0 1 2 3 4 5 6 7 8 9 10 11 12 13 14', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='new_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='new_list',
            field=models.CharField(default='0 1 2 3 4 5 6 7 8 9 10 11 12 13 14', max_length=100),
        ),
    ]
