# Generated by Django 3.2.8 on 2021-11-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20211104_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='familiar_list',
            field=models.CharField(default='[2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414]', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='known_list',
            field=models.CharField(default='[2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414]', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_list',
            field=models.CharField(default='[2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414]', max_length=100),
        ),
    ]
